- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  become: true
  tasks:
    - name: copy file 
      file:
        src: "flaskr/init.d/flaskr"
        dest: "/etc/rc.d/init.d"
      dnf:
        name: python-flash
        state: absent
      git:
        repo: "https://github.com/llee2222/flaskr.git"
        dest: "/home/vagrant/srv/flaskr" 
